NUM_EPOCH : 5
NUM_CLASSES: 10

learning_rate: 5e-4
batch_size: 128

split_label_unlabel: 0.1

AL_Method: MNLP #ContrAL #wo_AL #EGL  #LC #MNLP #BALD 

num_samples: 500 #количество семплов, выбираемых каждый шаг АЛ